### ISSUE TITLE
Implement the Type Maze

### ISSUE THREAD

**Issue by hato1883** [hato1883/1DL201-Project-Group-9#1]
Create a data structure to store a NxM maze that holds N rows and M columns.

Bonus if there is a way to force each row to be M columns to prevent any non rectangular shapes.

Document usage and any invariants to reduce future documentation overhead.

Save in maze.ts file which will hold a Maze generation and modification code.
Export type for usage in other part of code base.

Remeber that all Issues should be implemented in a separate branch named

`feature-$/short-desc`

Where `$` is the issue number and `short-desc` is a short description of what the issue was about.
for this issue it can be `feature-1/add-maze-type`

**Comment by sisu6828** [comment]
fixed with the merge of #13
