### ISSUE TITLE
Stream for dfs

### ISSUE THREAD

**Issue by HiroItb** [hato1883/1DL201-Project-Group-9#22]
Extend the dfs algoritm to store needed data in a record and compatible with stream.

**Comment by HiroItb** [comment]
Jag tror att dfs med stream är fixad men när jag kör jest test får jag något kontigt type error.
![Skärmbild 2024-02-21 210345](https://github.com/hato1883/1DL201-Project-Group-9/assets/144328978/6b78914c-0e0b-43ee-b2cf-aa312bc8a18c)
![Skärmbild 2024-02-21 211414](https://github.com/hato1883/1DL201-Project-Group-9/assets/144328978/a1f0384b-2422-43b3-9257-4f2846ce682a)
![Skärmbild 2024-02-21 211431](https://github.com/hato1883/1DL201-Project-Group-9/assets/144328978/4672e9ce-ddd7-48f7-9255-fce6ef7a7528)
![Skärmbild 2024-02-21 211503](https://github.com/hato1883/1DL201-Project-Group-9/assets/144328978/a30b6315-742e-4538-aa05-d34aedd45b18)
Ser dfs okej ut?

**Comment by hato1883** [comment]
lite oklart, jag hade dock tråkigt igår och fixade dfs (sorry).
Men din lössning är om inget annat typ 99% där svårt at felsöka utan koden framför mig i editorn dock.
