### ISSUE TITLE
Update user interface

### ISSUE THREAD

**Issue by hato1883** [hato1883/1DL201-Project-Group-9#25]
Currently when you reload the webpage the app runs immediately,
It would be cool if we added a main menu that you can select how many and which algorithms to run.

**1 - 4 algorithms**
**We want squares for each algorithm**

### This is a example layout, but feel free to be creative.

if 1 is selected it will get large portion of screen,
![image](https://github.com/hato1883/1DL201-Project-Group-9/assets/136370606/f6b8383d-5325-4c91-bb94-65406771a13d)

if 2 are selected they will each get a half of screen
![image](https://github.com/hato1883/1DL201-Project-Group-9/assets/136370606/025a9313-4ac2-4a18-9f1e-f79426458990)

if 3 are selected then we will divide the width in 3 and give them height equal to 1/3 of width
![image](https://github.com/hato1883/1DL201-Project-Group-9/assets/136370606/c963e94a-8691-4a91-b55e-de5518683c72)

if 4 then.
![image](https://github.com/hato1883/1DL201-Project-Group-9/assets/136370606/39ff10c2-bf19-4b7f-9d65-ca48adcda10a)

Each square should get a dropdown before starting that will be displaying all possible algorithms we can run.
When user has chossen a algorithm for all instances and press start which can be in the middle the simulation starts.

When simulation start we want to display the name of each choosen algorithm at the given instance.

### Other layout examples
![image](https://github.com/hato1883/1DL201-Project-Group-9/assets/136370606/1772b9b8-dc0f-4e8e-8126-1bcab03be545)
![image](https://github.com/hato1883/1DL201-Project-Group-9/assets/136370606/157ef342-35b0-4365-b64b-1508542e7e57)

**Comment by sisu6828** [comment]
I really like the first design alternative for 4 algorithms.

**Comment by hato1883** [comment]
Not Enough time to fix this.
