### ISSUE TITLE
Implement a ListGraph Type

### ISSUE THREAD

**Issue by hato1883** [hato1883/1DL201-Project-Group-9#4]
Fix a file named listgraph.ts that holds information on how a listgraph data is organized.
(most likely Array<list<number>>)

**Comment by HiroItb** [comment]
Jag har fått ett problem när jag kör npm run lint, för att se om den följer styleguiden.  Problemet "warning This line has a length of 87. Maximum allowed is 80  @stylistic/max-len" är för en funktion deklaration och säger att den är för lång.
![Skärmbild 2024-02-15 175924](https://github.com/hato1883/1DL201-Project-Group-9/assets/144328978/afa4767e-78ea-4d7b-9cda-5b7c1c6b8ec0)
Så om man försöker fixa det t.ex. så att man bryter den vid en av argumenten för funktionen och sätter den en rad under.
![Skärmbild 2024-02-15 180501](https://github.com/hato1883/1DL201-Project-Group-9/assets/144328978/fb523afd-28a3-4edb-9355-beb9e8ec75bf)
![Skärmbild 2024-02-15 180813](https://github.com/hato1883/1DL201-Project-Group-9/assets/144328978/1f8de95a-1e13-42d3-9366-249ccf4df786)

Får ett till style problem. Vet någon hur det kan fixas?

**Comment by hato1883** [comment]
Snygt att du hittade hit.
Det man kan göra är att dela upp funktionene på detta sätt:
![image](https://github.com/hato1883/1DL201-Project-Group-9/assets/136370606/de662023-947a-44e4-b90c-6da07536aa49)
dvs.
```ts
export function build_list<T>(fun: (i: number) => T, n: number): List<T> {
    function $build_list<T>(i: number,
                            fun: (i: number) => T,
                            already_built: List<T>): List<T> {
        return i < 0
            ? already_built
            : $build_list(i - 1, fun, pair(fun(i), already_built));
    }
    return $build_list(n - 1, fun, null);
}
```

Jag har gjort en updatering på development branchen för att fixa stilen på Ternary Expressions.
dvs
```ts
        return i < 0
            ? already_built
            : $build_list(i - 1, fun, pair(fun(i), already_built));
```
istället för
```ts
        return i < 0
                  ? already_built
                  : $build_list(i - 1, fun, pair(fun(i), already_built));
```
då alternativ 2 går inte att automatiskt kontrollera.

För att hämta det nya uppdateringarna kan du köra följande
```shell
git checkout development; git fetch; git pull; git checkout feature-4/add-listgraph-type; git merge development
```
eller rad för rad
```shell
git checkout development
git fetch
git pull
git checkout feature-4/add-listgraph-type
git merge development
```

Jag rekommederar stark att skaffa Eslint pluginet till vscode
![image](https://github.com/hato1883/1DL201-Project-Group-9/assets/136370606/83531fae-a672-4329-a9d9-4b7be3336b8d)
Om du har detta kommer den visa dig vart felet är i koden medan du skriver samt ibland ge dig en quickfix på enkla problem.

Plugins hittar du här:
![image](https://github.com/hato1883/1DL201-Project-Group-9/assets/136370606/d56a4232-dcdc-4a2f-98cf-a4643864acaa)

**Comment by HiroItb** [comment]
Tack för hjälpen, har nu commit & pushat modulerna graphs och list.

**Comment by hato1883** [comment]
snyggt! Kan du fixa en pull request ochså?
bra om all får testa, specielt nu när vi kör med code reviews :)

**Comment by HiroItb** [comment]
Ok, det ska finnas nu en pull request till development branchen.
